### ISSUE TITLE
Type Error with examples

### ISSUE THREAD

**Issue by amin-sagar** [mseok/PIGNet2#8]
Hello.
Thanks for this awesome work.
I tried the examples and I am getting an error similar to #5 with the updated code as well.
The error is
```
(pignet2) amin@BTX-CC1:~/softwares/PIGNet2$ python src/exe/predict.py ./src/ckpt/pda_0.pt -p examples/protein.pdb -l examples/ligand_single_conformation.sdf -o examples/case11.txt --no-prot-pdb --no-prot-sdf
Load from: /home/amin/softwares/PIGNet2/src/ckpt/pda_0.pt
Writing results to: /home/amin/softwares/PIGNet2/examples/case11.txt
device: device(type='cuda', index=0)
Traceback (most recent call last):
  File "/home/amin/softwares/PIGNet2/src/exe/predict.py", line 161, in <module>
    main(args)
  File "/home/amin/softwares/PIGNet2/src/exe/predict.py", line 106, in main
    data_list = [
  File "/home/amin/softwares/PIGNet2/src/exe/predict.py", line 107, in <listcomp>
    read_data(
  File "/home/amin/softwares/PIGNet2/src/exe/predict.py", line 68, in read_data
    datum = complex_to_data(ligand, mol_target, key=name, conv_range=conv_range)
  File "/home/amin/softwares/PIGNet2/src/data/data.py", line 271, in complex_to_data
    assert set(ligand.keys()) == set(target.keys())
TypeError: 'list' object is not callable
```
The torch-geometric version seems correct
```
mamba list | grep torch
torch                     1.9.1+cu111              pypi_0    pypi
torch-cluster             1.5.9                    pypi_0    pypi
torch-geometric           2.0.3                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.12                   pypi_0    pypi
torch-spline-conv         1.2.1                    pypi_0    pypi
```

I would be really grateful for any suggestions.
Best,
Amin.

**Comment by sangyeon-hits** [comment]
Hello.

In your case, you need the other way around: the `keys` attribute should be used as-is, not with `()`; that is,
```python
    assert set(ligand.keys) == set(target.keys)
```
